version: '3' #version of docker-compose
services:
  my-app:
    image: 442262966439.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
    ports:
      - 3000:3000
  mongodb: #name of container we wish to create
    image: mongo #name of image to create from
    ports:
     - 27017:27017 #port mapping
    environment: #environment variables for the containers
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db #postgres default storage is in /var/lib/postgresql/data
    #healthcheck: mongosh localhost:27017/test --quiet
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local
#no need to create a docker network for these 2 to live in, compose will auto create one for all services in it